### ISSUE TITLE
replace_ampersands.lua fails if locale is given on command line

### ISSUE THREAD

**Issue by njbart** [crsh/rmdfiltr#9]
`replace_ampersands.lua` works nicely if the locale is provided in the YAML metadata header, but fails with the error message shown below if the locale is given on pandoc’s command line.

Using the YAML metadata header:

```
pandoc -s --citeproc -L replace_ampersands.lua  -t plain << EOT

@item1

---
csl: apa.csl
references:
- id: item1
  type: book
  author:
    - family: Doe
      given: Jane
    - family: Roe
      given: Ron
  issued: 2020
  title: The title
  publisher: The Publisher
lang: en-GB
...
EOT
```

Output:

```
Doe and Roe (2020)

Doe, J., & Roe, R. (2020). The title. The Publisher.
```

Using the command line:

```
pandoc -s --citeproc -M lang=en-GB -L replace_ampersands.lua  -t plain << EOT

@item1

---
csl: apa.csl
references:
- id: item1
  type: book
  author:
    - family: Doe
      given: Jane
    - family: Roe
      given: Ron
  issued: 2020
  title: The title
  publisher: The Publisher
...
EOT
```

Output:

```
Error running filter /Users/nb/.local/share/pandoc/filters/replace_ampersands.lua:
...rs/nb/.local/share/pandoc/filters/replace_ampersands.lua:13: attempt to index a nil value (field '?')
stack traceback:
	...rs/nb/.local/share/pandoc/filters/replace_ampersands.lua:13: in function 'get_lang_tag'
```

Expected output: Same as when using the YAML metadata header – it shouldn’t make a difference by which way the `lang` field is being set.
